### ISSUE TITLE
Examples of Machine Translation Training

### ISSUE THREAD

**Issue by bityigoss** [princeton-nlp/TRIME#1]
Thanks for your excellent work~
can you provide a example of training a machine translation model on iwslt'14.de-en ?

**Comment by a3616001** [comment]
Thanks for your interest! 
Unfortunately, the current codebase doesn't include the code for the MT experiments yet. We'd like to also release that part. You may check back later.

**Comment by a3616001** [comment]
Hi @bityigoss , just a quick note that we have released the code for our machine translation experiments. Check it out if you are interested!
